name: Bug Report/Bug 反馈
description: File a bug report
title: "\u200b"
labels: ['bug']
body:
  - type: markdown
    attributes:
      value: 
        Thanks for taking the time to fill out this bug report!
        we will take care of it as soon as possible.
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?/Bug内容
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!/Bug内容填写在这
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Distribution version
      description: What version of AFFiNE are you using?
      options:
        - v1.3.4.1
        - v1.3.3.2
        - v1.3.3.1
    validations:
      required: true
  - type: dropdown
    id: browsers
      label: What browsers are you seeing the problem on if you're using web version?
      multiple: true
      options:
        - Chrome
        - Microsoft Edge
        - Firefox
        - Safari
        - Other
  - type: checkboxes
    id: selfhost
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!
        Tip: You can attach images here
